import os
import argparse

import pandas

import config
from data_source.ModelPreparator import ModelPreparator


argparse = argparse.ArgumentParser()
argparse.add_argument("-i", "--input-file", required=True, dest="input_file",
                      help="Input CSV file generated by data_extractor")
argparse.add_argument("-p", "--test-file-percent", required=True, dest="test_file_percent", type=int,
                      help="Percent of the date will be generated into a separate test file")
argparse.add_argument("-d", "--day-behind", required=True, dest="days_behind", type=int,
                      help="Days behind to be added for the model on each line")
args = vars(argparse.parse_args())

model_preparator = ModelPreparator()
dataframe, input_data, output_data = model_preparator.prepare(pandas.read_csv(args['input_file']), args['days_behind'])
file_components = os.path.splitext(args['input_file'])
new_data_file_name = '{0}_model{1}'.format(file_components[0], file_components[1])
dataframe.to_csv(new_data_file_name)
