import sys
import argparse

import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV


argparse = argparse.ArgumentParser()
argparse.add_argument("-i", "--input-file", required=True, dest="input_file",
                      help="Input CSV file generated by data_extractor")
args = vars(argparse.parse_args())


dataset = pd.read_csv(args['input_file']).dropna()
X = dataset.iloc[:, 3:].values
y = dataset.iloc[:, 2].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


def build_classifier(input_dim: int, optimizer: str):
    classifier = Sequential()
    inner_nodes = int(input_dim / 2)
    classifier.add(Dense(output_dim=inner_nodes, init='uniform', activation='relu', input_dim=input_dim))
    classifier.add(Dropout(p=0.1))
    classifier.add(Dense(output_dim=inner_nodes, init='uniform', activation='relu'))
    classifier.add(Dropout(p=0.1))
    classifier.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))
    classifier.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

    return classifier

classifier = KerasClassifier(build_fn=build_classifier)

# parameters = {
#     'input_dim': [X.shape[1]],
#     'batch_size': [9, 10, 11, 12],
#     'nb_epoch': [10, 20, 25],
#     'optimizer': ['adam', 'rmsprop']
# }
# grid_search = GridSearchCV(estimator=classifier, param_grid=parameters, scoring='accuracy', cv=5, n_jobs=-1)
# grid_search = grid_search.fit(X_train, y_train)
# best_parameters = grid_search.best_params_
# best_accuracy = grid_search.best_score_
# print(best_parameters, best_accuracy)

classifier = build_classifier(X.shape[1], 'rmsprop')
classifier.fit(X_train, y_train, batch_size=9, nb_epoch=20)

y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)


test_dataset = pd.read_csv('/home/ionescu/projects/python/home-automation/weather-predict/weather6h_model_test.csv').dropna()
XX = test_dataset.iloc[:, 3:].values
yy = test_dataset.iloc[:, 2].values

i = 0
good = 0
for test_data in XX:
    y_pred = classifier.predict(sc.transform(np.array([test_data])))
    will_rain = (y_pred > 0.5)
    if (will_rain == True and  yy[i] == 1) or (will_rain == False and yy[i] == 0):
        good += 1
    # print("Index: {0}, Actual: {1}, Percent pred: {2}, Predicted  {3}". format(i, yy[i], y_pred, will_rain))
    print("Index: {0}, Actual: {1}, Predicted  {2}". format(i, yy[i], will_rain))
    i += 1

print ('Total: {0}, Good: {1}, Percent accuracy: {2} ', i, good, good * 100 / i)

