import sys
import argparse

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

from machine_learning.ModelBuilder import ModelBuilder
from machine_learning.GridSearch import GridSearch


argparse = argparse.ArgumentParser()
argparse.add_argument("-f", "--input-file", required=True, dest="input_file",
                      help="Input CSV file generated by data_extractor")
argparse.add_argument("-t", "--test-file", required=True, dest="test_file",
                      help="Input CSV test file generated by data_extractor")
argparse.add_argument("-md", "--mode", required=True, dest="mode", choices=['grid', 'test'],
                      help="Mode of operations: grid  or test")
args = vars(argparse.parse_args())

model_builder = ModelBuilder()
grid_search = GridSearch(model_builder)


def read_from_csv(path: str) -> tuple:
    dataset = pd.read_csv(path).dropna()
    X = dataset.iloc[:, 2:].values
    y = dataset.iloc[:, 1].values
    return X, y

X, y = read_from_csv(args['input_file'])
sc = StandardScaler()
X = sc.fit_transform(X)

if args['mode'] == 'grid':
    print(grid_search.search(X, y))
    sys.exit()

classifier = model_builder.build(X.shape[1], 'adam', 0.1)
classifier.fit(X, y, batch_size=3, nb_epoch=10)
X_test, y_test = read_from_csv(args['test_file'])
i = good = 0

for test_data in X_test:
    y_pred = classifier.predict(sc.transform(np.array([test_data])))
    actual_rain = True if y_test[i] == 1 else False
    predicted_rain = (y_pred > 0.5)
    if (predicted_rain == True and y_test[i] == 1) or (predicted_rain == False and y_test[i] == 0):
        good += 1
    print("Index: {0}, Actual, Predicted: {1}|{2}". format(i, actual_rain, predicted_rain))
    i += 1

print ('Total: {0}, Good: {1}, Percent accuracy: {2} '.format(i, good, good * 100 / i))