conf = {
    'door': {
        'value': False,
        'type': 'single',
        'room' : 'holway',
        'device_type': 'door',
        'strategy' : 'send',
        'communicator': 'bluetooth',
        'send_to_device': 'holway',
        'encription': False,
        'command': {True: 'O'}
    },
    'homeAlarm': {
        'value': False,
        'type': 'bi',
        'device_type': 'action',
        'room' : 'general',
        'strategy' : False,
        'communicator': False,
        'send_to_device': False,
        'encription': False,
        'command': False
    },
    'livingCourtainsDwn': {
        'value': False,
        'type': 'single',
        'device_type': 'courtains',
        'room' : 'living',
        'strategy': 'send',
        'communicator': 'serial',
        'encription': 'aes',
        'send_to_device': 'L2',
        'command': {True: 'C3|'}
    },
    'livingCourtainsUp': {
        'value': False,
        'type': 'single',
        'device_type': 'courtains',
        'room' : 'living',
        'strategy': 'send',
        'communicator': 'serial',
        'encription': 'aes',
        'send_to_device': 'L2',
        'command': {True: 'O3|'}
    },
    'closeAllLights': {
        'value': False,
        'type': 'single',
        'device_type': 'action',
        'room' : 'general',
        'strategy': 'group',
        'futureState': False,
        'actuators' : ['livingLight', 'bedroomLight', 'kitchenLight', 'holwayLight', 'closetLight', 'balconyLight'],
        'communicator': False,
        'send_to_device': False,
        'command': False,
        'encription': False,
    },
    'livingCourtains': {
        'value': False,
        'type': 'bi',
        'device_type': 'courtains',
        'room' : 'living',
        'strategy': 'send',
        'communicator': 'serial',
        'encription': 'aes',
        'send_to_device': 'L2',
        'command': {False: 'O90|', True: 'C90|'}
    },
    'livingLight': {
        'value': False,
        'type': 'bi',
        'device_type': 'light',
        'room' : 'living',
        'strategy': 'send',
        'communicator': 'serial',
        'encription': 'aes',
        'send_to_device': 'L1',
        'command': {False: '1C|', True: '1O|'}
    },
    'bedroomLight': {
        'value': False,
        'type': 'bi',
        'device_type': 'light',
        'room' : 'bedroom',
        'strategy': 'send',
        'communicator': 'serial',
        'encription': 'aes',
        'send_to_device': 'L1',
        'command': {False: '2C|', True: '2O|'}
    },
    'kitchenLight': {
        'value': False,
        'type': 'bi',
        'device_type': 'light',
        'room' : 'kitchen',
        'strategy': 'send',
        'communicator': 'serial',
        'encription': 'aes',
        'send_to_device': 'L1',
        'command': {False: '4C|', True: '4O|'}
    },
    'holwayLight': {
        'value': False,
        'type': 'bi',
        'device_type': 'light',
        'room': 'holway',
        'strategy': 'send',
        'communicator': 'serial',
        'encription': 'aes',
        'send_to_device': 'L1',
        'command': {False: '3C|', True: '3O|'}
    },
    'closetLight': {
        'value': False,
        'type': 'bi',
        'device_type': 'light',
        'room': 'closet',
        'strategy': 'send',
        'communicator': 'serial',
        'encription': 'aes',
        'send_to_device': 'L1',
        'command': {False: '5C|', True: '5O|'}
    },
    'balconyLight': {
        'value': False,
        'type': 'bi',
        'device_type': 'light',
        'room': 'balcony',
        'strategy': 'send',
        'communicator': 'serial',
        'encription': 'aes',
        'send_to_device': 'L1',
        'command': {False: '6C|', True: '6O|'}
    },
    'powerSocket1': {
        'value': False,
        'type': 'bi',
        'device_type': 'powerSocket',
        'room': 'living',
        'strategy': 'send',
        'communicator': 'serial',
        'encription': 'aes',
        'send_to_device': 'L1',
        'command': {False: '8C|', True: '8O|'}
    },
    'wemoSwitch1': {
        'value': False,
        'type': 'bi',
        'device_type': 'powerSocket',
        'room': 'holway',
        'strategy': 'wemo-switch',
        'communicator': False,
        'send_to_device': 'DanSwitch1',
        'command': False,
        'encription': False,
    },
    'zwaveSwitch1': {
        'value': False,
        'type': 'bi',
        'device_type': 'powerSocket',
        'room': 'living',
        'strategy': 'zwave-switch',
        'communicator' : False,
        'send_to_device': '0184f904.2.25.1.0',
        'command': False,
        'encription': False
    },
    'fibaroGreen' : {
        'value': False,
        'type': 'dimmer',
        'device_type': 'dimmer',
        'room': 'living',
        'strategy': 'zwave-switch',
        'communicator': False,
        'send_to_device': '0184f904.3.26.4.0',
        'command': False,
        'encription': False
    },
    'fibaroBlue' : {
        'value': False,
        'type': 'dimmer',
        'device_type': 'dimmer',
        'room': 'living',
        'strategy': 'zwave-switch',
        'communicator': False,
        'send_to_device': '0184f904.3.26.5.0',
        'command': False,
        'encription': False
    }
}