conf = [
    {
        'id' : 'humidity_living',
        'type' : 'humidity',
        'value' : 0,
        'location': 'living',
        'communication_code': ('H', False),
    },
    {
        'id' : 'humidity_outside',
        'type': 'humidity',
        'value': 0,
        'location': 'outside',
        'communication_code': ('H', '1'),
    },
    {
        'id' : 'temperature_living',
        'type' : 'temperature',
        'value' : 0,
        'visible' : ['graphs', 'homepage'],
        'location': 'living',
        'communication_code': ('T', False),
    },
    {
        'id' : 'temperature_outside',
        'type' : 'temperature',
        'value' : 0,
        'location' : 'outside',
        'communication_code': ('T', '1'),
    },
    {
        'id' : 'airPressure_outside',
        'type': 'airPressure',
        'value': 0,
        'location' : 'outside',
        'communication_code': ('PS', '1'),
    },
    {
        'id' : 'light_living',
        'type' : 'light',
        'value' : 0,
        'location' : 'living',
        'communication_code': ('L', False),
    },
    {
        'id' : 'light_outside',
        'type': 'light',
        'value': 0,
        'location': 'outside',
        'communication_code': ('L', '1'),
    },
    {
        'id' : 'voltage_outside',
        'type': 'voltage',
        'value': 0,
        'location': 'outside',
        'communication_code': ('V', '1'),
    },
    {
        'id' : 'rain_outside',
        'type' : 'rain',
        'value' : 0,
        'location': 'outside',
        'communication_code': ('R', '1'),
    },
    {
        'id' : 'presence_holway',
        'type' : 'presence',
        'value' : 0,
        'location': 'holway',
        'communication_code': ('P', False),
    },
    {
        'id' : 'airPollution_living',
        'type' : 'airPollution',
        'value' : 0,
        'location': 'living',
        'communication_code': ('Q', False),
    },
    {
        'id' : 'fingerprint_outside',
        'type' : 'fingerprint',
        'value' : 0,
        'location': 'outside',
        'communication_code': ('F', False),
    },
    {
        'id' : 'phoneIsHome',
        'type' : 'phoneIsHome',
        'value' : False,
        'location': 'outside',
    },
    {
        'id' : 'power_holway',
        'type' : 'power',
        'value': 0,
        'location': 'holway',
        'communication_code' : ('W', False),
    },
    {
        'id': '0184f904.2.31.1.4',
        'type': 'power',
        'value': 0,
        'location': 'living',
    }
]